# -*- coding: utf-8 -*-
"""RISHIKA Formation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jy-NxIj6TXSb9KCgiXV3CBlXWdQojcAl
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# --- Configuration ---
NAME = "RISHIKA"
N = 20           # Number of agents
P = 0.35         # Erdős-Rényi edge probability
DT = 0.04        # Integration step size
STEPS_PER_LETTER = 100
KP = 0.8         # Target proportional gain

# 1. Generate Connected Erdős-Rényi Graph
G = nx.erdos_renyi_graph(N, P)
while not nx.is_connected(G):
    G = nx.erdos_renyi_graph(N, P)

L = nx.laplacian_matrix(G).toarray()
L_kron = np.kron(L, np.eye(2))

# 2. Target Coordinates in R^2 for Letters in "RISHIKA"
def generate_letter_coords(char, N=20):
    char = char.upper()
    if char == 'R':
        v = np.column_stack([-1*np.ones(8), np.linspace(-1, 1, 8)])
        th = np.linspace(-np.pi/2, np.pi/2, 6)
        c = np.column_stack([-1 + 0.8*np.cos(th), 0.5 + 0.5*np.sin(th)])
        d = np.column_stack([np.linspace(-1, 0.6, 6), np.linspace(0, -1, 6)])
        pts = np.vstack([v, c, d])
    elif char == 'I':
        v = np.column_stack([np.zeros(10), np.linspace(-1, 1, 10)])
        top = np.column_stack([np.linspace(-0.8, 0.8, 5), np.ones(5)])
        bot = np.column_stack([np.linspace(-0.8, 0.8, 5), -np.ones(5)])
        pts = np.vstack([v, top, bot])
    elif char == 'S':
        th1 = np.linspace(0, 1.2*np.pi, 10)
        th2 = np.linspace(0, 1.2*np.pi, 10)
        c1 = np.column_stack([0.4*np.cos(th1), 0.5 + 0.5*np.sin(th1)])
        c2 = np.column_stack([-0.4*np.cos(th2), -0.5 - 0.5*np.sin(th2)])
        pts = np.vstack([c1, c2])
    elif char == 'H':
        v1 = np.column_stack([-0.8*np.ones(8), np.linspace(-1, 1, 8)])
        v2 = np.column_stack([0.8*np.ones(8), np.linspace(-1, 1, 8)])
        mid = np.column_stack([np.linspace(-0.8, 0.8, 4), np.zeros(4)])
        pts = np.vstack([v1, v2, mid])
    elif char == 'K':
        v = np.column_stack([-0.8*np.ones(8), np.linspace(-1, 1, 8)])
        d1 = np.column_stack([np.linspace(-0.8, 0.8, 6), np.linspace(0, 1, 6)])
        d2 = np.column_stack([np.linspace(-0.8, 0.8, 6), np.linspace(0, -1, 6)])
        pts = np.vstack([v, d1, d2])
    elif char == 'A':
        p1 = np.column_stack([np.linspace(-0.8, 0, 7), np.linspace(-1, 1, 7)])
        p2 = np.column_stack([np.linspace(0, 0.8, 7), np.linspace(1, -1, 7)])
        p3 = np.column_stack([np.linspace(-0.4, 0.4, 6), np.zeros(6)])
        pts = np.vstack([p1, p2, p3])
    else:
        th = np.linspace(0, 2*np.pi, N, endpoint=False)
        pts = np.column_stack([np.cos(th), np.sin(th)])

    indices = np.linspace(0, len(pts)-1, N, dtype=int)
    return pts[indices]

# 3. Trajectory Simulation Loop
np.random.seed(42)
x_curr = np.random.uniform(-4, 4, size=(N, 2)).flatten()
trajectory = [x_curr.reshape(N, 2)]
frame_letters = ["Initial"]

for char in NAME:
    target = generate_letter_coords(char, N).flatten()
    for _ in range(STEPS_PER_LETTER):
        error = x_curr - target
        dxdt = - L_kron @ error - KP * error
        x_curr = x_curr + DT * dxdt
        trajectory.append(x_curr.reshape(N, 2))
        frame_letters.append(char)

trajectory = np.array(trajectory)

# 4. Visualization and Animation Export
fig, ax = plt.subplots(figsize=(6, 6))
ax.set_xlim(-2.5, 2.5)
ax.set_ylim(-2.5, 2.5)
ax.set_aspect('equal')
ax.grid(True, linestyle='--', alpha=0.5)

lines = [ax.plot([], [], 'gray', alpha=0.4, lw=1)[0] for _ in G.edges()]
scatter = ax.scatter([], [], c='crimson', s=70, zorder=3)
title_text = ax.set_title("", fontsize=14, fontweight='bold')

def update(frame):
    pos = trajectory[frame]
    scatter.set_offsets(pos)
    for idx, (i, j) in enumerate(G.edges()):
        lines[idx].set_data([pos[i, 0], pos[j, 0]], [pos[i, 1], pos[j, 1]])

    current_char = frame_letters[frame]
    title_text.set_text(f"Formation Control — Letter: {current_char}")
    return scatter, *lines, title_text

ani = animation.FuncAnimation(fig, update, frames=len(trajectory), interval=40, blit=True)

writer = animation.FFMpegWriter(fps=25)
ani.save('rishika_formation.mp4', writer=writer)

print("Simulation finished. Output saved as 'rishika_formation.mp4'.")

